/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>
#include <opencv2/core/core.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/features2d/features2d.hpp>
#include <vector>
#include <queue>
using namespace cv ;
using namespace std ;
/* Header for class opencv_mokadem_ahmed_eyetracker_NativeClass */

#ifndef _Included_opencv_mokadem_ahmed_eyetracker_NativeClass
#define _Included_opencv_mokadem_ahmed_eyetracker_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     opencv_mokadem_ahmed_eyetracker_NativeClass
 * Method:    FindFeatures
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_opencv_mokadem_ahmed_eyetracker_NativeClass_FindFeatures
  (JNIEnv *, jclass, jlong, jlong);
JNIEXPORT jstring JNICALL Java_opencv_mokadem_ahmed_eyetracker_NativeClass_FindCenter
        (JNIEnv *env, jclass, jlong addFace, jint xeye,jlong yeye,jlong weye ,jlong heye);

#ifdef __cplusplus
}
#endif
#endif
